# Generated by Django 2.1.4 on 2019-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunBo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='LunBo_URL',
            field=models.ImageField(upload_to='img'),
        ),
    ]
