# Generated by Django 2.1.4 on 2019-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunBo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='LunBo_Info',
            field=models.CharField(max_length=50, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='LunBo_URL',
            field=models.ImageField(upload_to='LunBo', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='LunBo_title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
    ]
