# Generated by Django 2.1.4 on 2019-01-23 05:35

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunBo', '0004_auto_20190123_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='LunBo_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='LunBo_URL',
            field=models.ImageField(blank=True, upload_to='LunBo', verbose_name='图片'),
        ),
    ]
