# Generated by Django 2.1.4 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunBo', '0007_lunbo_jukalail_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lunbo',
            old_name='Jukalail_UserName',
            new_name='LunBo_UserName',
        ),
        migrations.AddField(
            model_name='lunbo',
            name='LunBo_Index',
            field=models.IntegerField(default=2, verbose_name='排序'),
        ),
    ]
