# Generated by Django 2.1.4 on 2019-01-16 05:26

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_review', '0002_auto_20190114_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film_review',
            options={'verbose_name': '影评', 'verbose_name_plural': '影评'},
        ),
        migrations.AlterField(
            model_name='film_review',
            name='f_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
