# Generated by Django 2.1.4 on 2019-01-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film_review', '0003_auto_20190116_0526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film_review',
            options={'verbose_name': '影评大', 'verbose_name_plural': '影评大'},
        ),
    ]
