# Generated by Django 2.1.4 on 2019-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuKaLaiLe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jukalai_l',
            name='Jukalail_Info',
            field=models.CharField(max_length=50, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='jukalai_l',
            name='Jukalail_URL',
            field=models.ImageField(upload_to='JuKaLaiLe', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='jukalai_l',
            name='Jukalail_title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
    ]
