# Generated by Django 2.1.4 on 2019-01-23 05:29

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuKaLaiLe', '0004_auto_20190122_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jukalai_l',
            name='Jukalail_Info',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='jukalai_l_xd',
            name='Jukalail_Info',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
