# Generated by Django 2.1.4 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuKaLaiLe', '0008_auto_20190125_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jukalai_L_Xd',
        ),
        migrations.AlterModelOptions(
            name='jukalai_l',
            options={'verbose_name': '剧咖来了', 'verbose_name_plural': '剧咖来了'},
        ),
        migrations.AddField(
            model_name='jukalai_l',
            name='Jukalail_Index',
            field=models.IntegerField(default=2, verbose_name='排序'),
        ),
    ]
