# Generated by Django 2.1.4 on 2019-02-23 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JuKaLaiLe', '0009_auto_20190125_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='jukalai_l',
            name='Jukalail_LaiYuan',
            field=models.CharField(default='', max_length=30, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='jukalai_l',
            name='Jukalail_RiQi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jukalai_l',
            name='Jukalail_Type',
            field=models.CharField(default='', max_length=30, verbose_name='分类'),
        ),
    ]
