# Generated by Django 2.1.4 on 2019-01-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tv_Title', models.CharField(max_length=30)),
                ('Tv_Url', models.ImageField(upload_to='img')),
                ('Tv_Info', models.CharField(max_length=50)),
            ],
        ),
    ]
