# Generated by Django 2.1.4 on 2019-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_play',
            name='Tv_Info',
            field=models.CharField(max_length=50, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='tv_play',
            name='Tv_Title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='tv_play',
            name='Tv_Url',
            field=models.ImageField(upload_to='TV_Play', verbose_name='图片'),
        ),
    ]
