# Generated by Django 2.1.4 on 2019-01-16 05:26

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Play', '0002_auto_20190114_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv_play',
            options={'verbose_name': '电视剧', 'verbose_name_plural': '电视剧'},
        ),
        migrations.AlterField(
            model_name='tv_play',
            name='Tv_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
