# Generated by Django 2.1.4 on 2019-01-21 09:20

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Play', '0003_auto_20190116_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_Play_xd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tv_Title', models.CharField(max_length=30, verbose_name='标题')),
                ('Tv_Url', models.ImageField(upload_to='TV_Play', verbose_name='图片')),
                ('Tv_Info', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '电视剧小',
                'verbose_name_plural': '电视剧小',
            },
        ),
        migrations.AlterModelOptions(
            name='tv_play',
            options={'verbose_name': '电视剧大', 'verbose_name_plural': '电视剧大'},
        ),
    ]
