# Generated by Django 2.1.4 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Play', '0008_auto_20190125_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tv_Play_xd',
        ),
        migrations.AlterModelOptions(
            name='tv_play',
            options={'verbose_name': '电视剧', 'verbose_name_plural': '电视剧'},
        ),
        migrations.RenameField(
            model_name='tv_play',
            old_name='Jukalail_UserName',
            new_name='TV_UserName',
        ),
        migrations.AddField(
            model_name='tv_play',
            name='TV_Index',
            field=models.IntegerField(default=2, verbose_name='排序'),
        ),
    ]
