# Generated by Django 2.1.4 on 2019-02-23 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Play', '0009_auto_20190125_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_play',
            name='Tv_Type',
            field=models.CharField(default='', max_length=30, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='tv_play',
            name='Ty_LaiY',
            field=models.CharField(default='', max_length=30, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='tv_play',
            name='Ty_RiQi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
    ]
