# Generated by Django 2.1.4 on 2019-01-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZhuanFang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_zhuanfang',
            name='ZhuanFang_Keyword',
            field=models.CharField(default='', max_length=50, verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='find_zhuanfang_xd',
            name='ZhuanFang_Keyword',
            field=models.CharField(default='', max_length=50, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='find_zhuanfang',
            name='ZhuanFang_sTitle',
            field=models.CharField(default='', max_length=50, verbose_name='小标题'),
        ),
        migrations.AlterField(
            model_name='find_zhuanfang_xd',
            name='ZhuanFang_sTitle',
            field=models.CharField(default='', max_length=50, verbose_name='小标题'),
        ),
    ]
