# Generated by Django 2.1.4 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZhuanFang', '0003_auto_20190125_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Find_ZhuanFang_XD',
        ),
        migrations.AlterModelOptions(
            name='find_zhuanfang',
            options={'verbose_name': '专访', 'verbose_name_plural': '专访'},
        ),
        migrations.RenameField(
            model_name='find_zhuanfang',
            old_name='Jukalail_UserName',
            new_name='ZhuanFang_UserName',
        ),
        migrations.AddField(
            model_name='find_zhuanfang',
            name='ZhuanFang_Index',
            field=models.IntegerField(default=2, verbose_name='排序'),
        ),
    ]
