# Generated by Django 2.1.4 on 2019-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZhuanFang', '0004_auto_20190125_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='find_zhuanfang',
            options={'verbose_name': '专访1', 'verbose_name_plural': '专访1'},
        ),
    ]
