# Generated by Django 2.1.4 on 2019-01-16 05:26

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Star', '0002_auto_20190114_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='find_star_info',
            options={'verbose_name': '明星', 'verbose_name_plural': '明星'},
        ),
        migrations.AlterField(
            model_name='find_star_info',
            name='Star_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
