# Generated by Django 2.1.4 on 2019-02-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star', '0010_find_star_info_star_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_star_info',
            name='Star_LaiY',
            field=models.CharField(default='', max_length=30, verbose_name='来源'),
        ),
    ]
