# Generated by Django 2.1.4 on 2019-02-23 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Star', '0011_find_star_info_star_laiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_star_info',
            name='Star_RiQi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
    ]
