# Generated by Django 2.1.4 on 2019-01-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='welfare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Welfare_title', models.CharField(max_length=50)),
                ('Walfare_URL', models.ImageField(upload_to='img')),
            ],
        ),
    ]
