# Generated by Django 2.1.4 on 2019-01-23 05:35

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welfare', '0004_auto_20190123_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find_welfare_info',
            name='Walfare_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='find_welfare_info',
            name='Walfare_Url',
            field=models.ImageField(blank=True, upload_to='Welfare', verbose_name='图片'),
        ),
    ]
