# Generated by Django 2.1.4 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Welfare', '0007_find_welfare_info_jukalail_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find_welfare_info',
            old_name='Jukalail_UserName',
            new_name='Welfare_UserName',
        ),
        migrations.AddField(
            model_name='find_welfare_info',
            name='Welfare_Index',
            field=models.IntegerField(default=2, verbose_name='排序'),
        ),
    ]
