# Generated by Django 2.1.4 on 2019-01-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Star_Title', models.CharField(max_length=30)),
                ('Star_Url', models.ImageField(upload_to='img')),
                ('Star_Info', models.CharField(max_length=50)),
            ],
        ),
    ]
