# Generated by Django 2.1.4 on 2019-01-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star_Photos', '0005_auto_20190123_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_photos',
            name='Star_Title_Keyword',
            field=models.CharField(default='', max_length=30, verbose_name='关键词'),
        ),
    ]
