# Generated by Django 2.1.4 on 2019-01-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star_Photos', '0006_star_photos_star_title_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_photos',
            name='Jukalail_UserName',
            field=models.CharField(default='', max_length=30, verbose_name='编辑名称'),
        ),
    ]
