# Generated by Django 2.1.4 on 2018-12-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_column', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.ImageField(upload_to='Movie'),
        ),
    ]
