# Generated by Django 2.1.4 on 2019-01-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_column', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_xiaode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='Movie', verbose_name='图片')),
                ('Movie_Title', models.CharField(max_length=30, verbose_name='标题')),
                ('Movie_Info', models.CharField(max_length=150, verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Info',
            field=models.CharField(max_length=150, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.ImageField(upload_to='Movie', verbose_name='图片'),
        ),
    ]
