# Generated by Django 2.1.4 on 2019-01-16 05:26

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_column', '0002_auto_20190114_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影大', 'verbose_name_plural': '电影大'},
        ),
        migrations.AlterModelOptions(
            name='movie_xiaode',
            options={'verbose_name': '电影小', 'verbose_name_plural': '电影小'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='Movie_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='movie_xiaode',
            name='Movie_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
