# Generated by Django 2.1.4 on 2019-01-23 05:35

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_column', '0004_auto_20190123_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='Movie', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='movie_xiaode',
            name='Movie_Info',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='movie_xiaode',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='Movie', verbose_name='图片'),
        ),
    ]
