# Generated by Django 2.1.4 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_column', '0007_auto_20190125_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie_xiaode',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Jukalail_UserName',
            new_name='Movie_UserName',
        ),
        migrations.AddField(
            model_name='movie',
            name='Movie_Index',
            field=models.IntegerField(default=2, verbose_name='排序'),
        ),
    ]
