# Generated by Django 2.1.4 on 2019-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_column', '0009_auto_20190223_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Movie_RiQi',
            field=models.DateTimeField(auto_now=True, verbose_name='发布日期'),
        ),
    ]
