# Generated by Django 2.1.4 on 2019-02-23 09:01

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeHua_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CeHua_Title', models.CharField(max_length=30, verbose_name='标题')),
                ('CeHua_Title_Keyword', models.CharField(default='', max_length=30, verbose_name='关键词')),
                ('CeHua_UserName', models.CharField(default='', max_length=30, verbose_name='编辑名称')),
                ('CeHua_Index', models.IntegerField(default=2, verbose_name='排序')),
                ('CeHua_Url', models.ImageField(blank=True, upload_to='Star_Photos', verbose_name='图片')),
                ('CeHua_Info', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '明星美图',
                'verbose_name_plural': '明星美图',
            },
        ),
    ]
