# Generated by Django 2.1.4 on 2019-02-23 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CeHua', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cehua_photos',
            options={'verbose_name': '策划', 'verbose_name_plural': '策划'},
        ),
        migrations.AddField(
            model_name='cehua_photos',
            name='CeHua_LaiYuan',
            field=models.CharField(default='', max_length=30, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='cehua_photos',
            name='CeHua_RiQi',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cehua_photos',
            name='CeHua_Url',
            field=models.ImageField(blank=True, upload_to='CeHua_Photos', verbose_name='图片'),
        ),
    ]
